name: GithubCounter
options:
  bundleIdPrefix: io.githubcounter
  deploymentTarget:
    macOS: 14.0
targets:
  GithubCounter:
    type: application
    platform: macOS
    sources: 
      - GithubCounter
      - Shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: io.githubcounter.GithubCounterApp
      CODE_SIGN_IDENTITY: "-"
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: ""
      GENERATE_INFOPLIST_FILE: YES
      CURRENT_PROJECT_VERSION: 12
      MARKETING_VERSION: 1.0.8
      ENABLE_USER_SCRIPT_SANDBOX: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: GithubCounter/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: "Github Counter URL"
            CFBundleURLSchemes:
              - githubcounter


    dependencies:
      - target: GithubCounterWidget
      - sdk: AppIntents.framework
      - sdk: WidgetKit.framework
  GithubCounterWidget:
    type: app-extension
    platform: macOS
    sources: 
      - GithubCounterWidget
      - Shared
    info:
      path: GithubCounterWidget/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.8"
        CFBundleVersion: "12"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      CODE_SIGN_IDENTITY: "-"
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: ""
      CURRENT_PROJECT_VERSION: 12
      MARKETING_VERSION: 1.0.8
      PRODUCT_BUNDLE_IDENTIFIER: io.githubcounter.GithubCounterApp.Widget
      EXCLUDED_ARCHS: ""
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: GithubCounterWidget/GithubCounterWidget.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
    dependencies:
      - sdk: AppIntents.framework
      - sdk: WidgetKit.framework

